### PR TITLE
Fix link to lambda code (python repo, not javascript)

### PR DESCRIPTION
**Pull request by nedlowe**

### CODE REVIEW

**Comment by panth** [comment]
The python github link is not working

**Comment by nedlowe** [comment]
Are you sure?  Works for me...

**Comment by panth** [comment]
Ok saw it now. Sorry was referring to incorrect location.

Speaking on this sample code , is there any advanced version of this code , wherein the inline facts could be picked up from say some database based on the question asked as interpreted from the intent ?

Cheers
Himanshu Pant

**Comment by franklin-lobb** [comment]
issue seems to have already been resolved through another updated

**Pull request closed without merging**
